server:
  root: path/YoupiBanane/
  name: serverOne
  listen:
    host: 127.0.0.1
    port: 8080
  listen:
    host: 0.0.0.0
    port: 7070
  location:
    root: path/YoupiBanane/nop/
    route: /directory
    index: other.pouic
    allow_method: GET
    cgi: bla

server:
  root: path/YoupiBanane/
  name: serverTwo
  listen:
    host: 127.0.0.1
    port: 8000
