server:
  root: path/YoupiBanane/
  name: serverOne
  listen:
    host: 127.0.0.1
    port: 8080
  listen:
    host: 0.0.0.0
    port: 7070
  location:
    root: ./path/YoupiBanane
    route: /
    index: index.html
    allow_method: GET
    cgi: bla
  location:
    root: ./path/YoupiBanane/Yeah
    route: /direc/
    index: index.html
    index: not_happy.bad_extension
    allow_method: GET
    allow_method: PUT
    cgi: bla

server:
  root: path/YoupiBanane/
  name: serverTwo
  listen:
    host: 127.0.0.1
    port: 8000
