server:
  root: path/YoupiBanane
  name: serverOne
  listen:
    host: 127.0.0.1
    port: 8080
  listen:
    host: 0.0.0.0
    port: 7070
  location:
    allow_method: GET
    route: /directory
    cgi: bla

server:
  root: path/jklse
  name: serverTwo
  listen:
    host: 127.0.0.1
    port: 8000
