server:
  root: path/YoupiBanane/
  name: serverOne
  cgi_path: tests/cgi_tester
  max_request_size: 2500
  timeout: 30
  error_page:
    path: ./errors/error.html
    status_code: 404
  listen:
    host: 127.0.0.1
    port: 8080
  listen:
    host: 0.0.0.0
    port: 7070
  location:
    route: /
    root: ./path/YoupiBanane
    index: index.html
    allow_method: GET
    allow_method: PUT
    directory_listing: true
    cgi: bla
  location:
    route: /direc/
    root: ./path/YoupiBanane/Yeah
    index: index.html
    index: not_happy.bad_extension
    allow_method: GET
    allow_method: DELETE
    allow_method: POST
    allow_method: PUT
    cgi: bla

server:
  root: path/YoupiBanane/
  name: testy
  cgi_path: test_ubuntu/ubuntu_cgi_tester
  listen:
    host: 127.0.0.1
    port: 8000
  location:
    route: /
    root: ./path/YoupiBanane
    index: index.html
    allow_method: GET
  location:
    route: /put_test/
    root: ./path/YoupiBanane/put_test
    allow_method: PUT
  location:
    route: /directory/
    root: ./path/YoupiBanane
    allow_method: GET
    allow_method: POST
    index: youpi.bad_extension
    cgi: bla
  location:
    route: /post_body/
    root: ./path/YoupiBanane
    allow_method: POST
    max_body_size: 100
